import type {
  Inquiry,
  KnowledgeCandidate,
  KnowledgeSource,
  ManualJob,
  ModelProvider,
  QualityIssue,
} from "./types";

// ※ 本データはモックです。機種名・数値・自治体名はすべて架空のものです。

export const MACHINES = [
  { code: "BM-S", name: "BM-S型 小口径削進機", range: "φ100〜150" },
  { code: "BM-M", name: "BM-M型 小口径削進機", range: "φ200〜250" },
  { code: "BM-L", name: "BM-L型 中口径削進機", range: "φ300〜400" },
  { code: "BM-R", name: "BM-R型 礫対応削進機", range: "φ200〜300（礫層）" },
];

export const inquiries: Inquiry[] = [
  {
    id: "INQ-2026-0912-03",
    receivedAt: "2026-09-12T09:42:00+09:00",
    client: "某市 下水道課",
    clientType: "自治体",
    title: "本管新設 φ200 推進延長 48m（砂質土）",
    workType: "本管新設（推進）",
    pipeDiameter: 200,
    length: 48,
    soil: "砂質土（細砂主体）",
    nValue: "N=8〜12",
    groundwater: "GL-2.1m",
    shaft: "発進立坑 φ2.5m ／ 到達立坑 φ2.0m",
    source: "PDF図面",
    status: "pending_review",
    proposal: {
      machine: "BM-M型 小口径削進機",
      fit: "◎",
      confidence: 91,
      estimate: 4_860_000,
      dailyAdvance: 8,
      durationDays: 6,
      rationale: [
        "管径 φ200・延長 48m は BM-M型 の標準適用範囲（φ200〜250、〜60m）に収まる",
        "砂質土 N=8〜12 は積算資料 2026年版 表3-2 の『砂質土 区分B』に該当",
        "地下水位 GL-2.1m は管底より上のため、補助工法（薬液注入）の要否を条件に加算",
      ],
      cautions: [
        "地下水位が管底より高いため、補助工法の要否を設計者へ確認すること",
        "到達立坑 φ2.0m は最小寸法。到達側の機材搬出手順に注意",
      ],
      references: [
        { doc: "積算資料 2026年版", page: "p.12 表3-2", label: "土質区分と日進量" },
        { doc: "積算資料 2026年版", page: "p.18 表5-1", label: "機種別 標準歩掛" },
        { doc: "参考資料（仕様書）", page: "p.7", label: "BM-M型 適用範囲" },
      ],
    },
  },
  {
    id: "INQ-2026-0912-02",
    receivedAt: "2026-09-12T09:05:00+09:00",
    client: "△△設計事務所",
    clientType: "設計事務所",
    title: "取付管 φ100 指定 延長 22m（礫混じり砂）",
    workType: "取付管（推進）",
    pipeDiameter: 100,
    length: 22,
    soil: "礫混じり砂（最大礫径 40mm）",
    nValue: "N=15〜20",
    groundwater: "GL-3.5m",
    shaft: "発進立坑 φ2.0m ／ 到達 既設人孔",
    source: "手書き図面",
    status: "pending_review",
    proposal: {
      machine: "BM-R型 礫対応削進機（φ200 へ変更提案）",
      fit: "△",
      confidence: 74,
      estimate: 3_120_000,
      dailyAdvance: 5,
      durationDays: 5,
      rationale: [
        "客先指定は φ100 だが、最大礫径 40mm の礫混じり砂では BM-S型（φ100）の排土能力を超える",
        "過去の類似案件 14件中 12件で φ200・BM-R型 へ変更して施工している（判断履歴 2023〜2026）",
        "仕様書上は φ100 でも『適用可』の記載だが、経験値では通らない可能性が高い",
      ],
      cautions: [
        "客先指定径からの変更提案となるため、設計者への説明資料が必要",
        "手書き図面のため、管底高・立坑位置の読み取り精度に注意（要目視確認）",
      ],
      references: [
        { doc: "参考資料（仕様書）", page: "p.5", label: "BM-S型 適用範囲（礫径 ≤ 20mm）" },
        { doc: "判断履歴", page: "2023-2026", label: "礫混じり砂 φ100指定 案件 14件" },
      ],
      deviationFromSpec:
        "仕様書では φ100（BM-S型）適用可だが、経験則上 礫径 40mm では φ200（BM-R型）を推奨。",
    },
  },
  {
    id: "INQ-2026-0912-01",
    receivedAt: "2026-09-12T08:30:00+09:00",
    client: "○○建設（協会加盟）",
    clientType: "協会加盟工事会社",
    title: "本管新設 φ300 推進延長 75m（粘性土）",
    workType: "本管新設（推進）",
    pipeDiameter: 300,
    length: 75,
    soil: "粘性土（シルト質）",
    nValue: "N=3〜6",
    groundwater: "GL-1.8m",
    shaft: "発進立坑 φ3.0m ／ 到達立坑 φ2.5m",
    source: "Excel",
    status: "pending_review",
    proposal: {
      machine: "BM-L型 中口径削進機",
      fit: "○",
      confidence: 83,
      estimate: 9_450_000,
      dailyAdvance: 6,
      durationDays: 13,
      rationale: [
        "φ300・75m は BM-L型 の適用範囲内だが、延長が標準（60m）を超えるため中間ジャッキの検討が必要",
        "軟弱粘性土（N=3〜6）は蛇行しやすく、日進量を標準の 8m/日 から 6m/日 に低減",
      ],
      cautions: [
        "延長 60m 超のため、推力計算と中間ジャッキ要否を積算担当が確認",
        "N値 5 以下の区間は方向制御の頻度が上がる。過去案件では工期 +2日 の実績あり",
      ],
      references: [
        { doc: "積算資料 2026年版", page: "p.14 表3-4", label: "軟弱土 日進量補正" },
        { doc: "参考資料（仕様書）", page: "p.9", label: "BM-L型 適用範囲・最大推進延長" },
      ],
    },
  },
  {
    id: "INQ-2026-0911-08",
    receivedAt: "2026-09-11T16:20:00+09:00",
    client: "□□町 上下水道課",
    clientType: "自治体",
    title: "本管新設 φ250 推進延長 35m（砂礫）",
    workType: "本管新設（推進）",
    pipeDiameter: 250,
    length: 35,
    soil: "砂礫（最大礫径 80mm）",
    nValue: "N=30以上",
    groundwater: "GL-4.0m",
    shaft: "発進立坑 φ2.5m ／ 到達立坑 φ2.5m",
    source: "PDF図面",
    status: "escalated",
    proposal: {
      machine: "BM-R型 礫対応削進機",
      fit: "△",
      confidence: 58,
      estimate: 5_900_000,
      dailyAdvance: 3,
      durationDays: 12,
      rationale: [
        "最大礫径 80mm は BM-R型 の上限（60mm）を超える。過去に同条件での施工実績が 2件しかない",
      ],
      cautions: ["実績が少なく信頼度が低い。現場経験者への相談を推奨"],
      references: [
        { doc: "参考資料（仕様書）", page: "p.11", label: "BM-R型 礫径上限" },
      ],
    },
    reviewer: "積算担当 A",
    reviewerNote: "礫径 80mm は判断が割れる。現場経験者（協会 技術委員）へ相談中。",
  },
  {
    id: "INQ-2026-0911-05",
    receivedAt: "2026-09-11T13:10:00+09:00",
    client: "◇◇市 下水道整備課",
    clientType: "自治体",
    title: "取付管 φ150 延長 18m（砂質土）",
    workType: "取付管（推進）",
    pipeDiameter: 150,
    length: 18,
    soil: "砂質土",
    nValue: "N=10〜15",
    groundwater: "GL-3.0m",
    shaft: "発進立坑 φ2.0m ／ 到達 既設人孔",
    source: "PDF図面",
    status: "approved",
    proposal: {
      machine: "BM-S型 小口径削進機",
      fit: "◎",
      confidence: 95,
      estimate: 1_980_000,
      dailyAdvance: 8,
      durationDays: 3,
      rationale: ["φ150・18m・砂質土は BM-S型 の最も標準的な適用条件"],
      cautions: [],
      references: [
        { doc: "積算資料 2026年版", page: "p.12 表3-2", label: "土質区分と日進量" },
      ],
    },
    reviewer: "積算担当 A",
    reviewerNote: "AI回答案どおりでOK。",
  },
  {
    id: "INQ-2026-0911-02",
    receivedAt: "2026-09-11T10:45:00+09:00",
    client: "▽▽設計コンサルタント",
    clientType: "設計事務所",
    title: "本管新設 φ200 推進延長 55m（粘性土・地下水高）",
    workType: "本管新設（推進）",
    pipeDiameter: 200,
    length: 55,
    soil: "粘性土",
    nValue: "N=4〜8",
    groundwater: "GL-1.2m",
    shaft: "発進立坑 φ2.5m ／ 到達立坑 φ2.0m",
    source: "PDF図面",
    status: "revised",
    proposal: {
      machine: "BM-M型 小口径削進機",
      fit: "○",
      confidence: 80,
      estimate: 5_200_000,
      dailyAdvance: 7,
      durationDays: 8,
      rationale: ["φ200・55m は BM-M型 適用範囲内"],
      cautions: ["地下水位が高いため補助工法を検討"],
      references: [
        { doc: "積算資料 2026年版", page: "p.12 表3-2", label: "土質区分と日進量" },
      ],
    },
    reviewer: "積算担当 A",
    reviewerNote:
      "地下水位 GL-1.2m で粘性土の場合、発進部の鏡切り時に湧水リスクが高い。薬液注入を『検討』ではなく『必須』として回答。工期 +2日。",
    learnedDelta:
      "条件: 粘性土 × 地下水位が管頂より 1.0m 以上高い → 補助工法（薬液注入）を必須扱い、工期 +2日",
  },
  {
    id: "INQ-2026-0910-04",
    receivedAt: "2026-09-10T15:00:00+09:00",
    client: "☆☆工業（協会加盟）",
    clientType: "協会加盟工事会社",
    title: "更生前 事前相談 φ250 延長 40m",
    workType: "事前相談",
    pipeDiameter: 250,
    length: 40,
    soil: "不明（ボーリング未実施）",
    nValue: "—",
    groundwater: "—",
    shaft: "未定",
    source: "電話",
    status: "approved",
    proposal: {
      machine: "BM-M型 小口径削進機（暫定）",
      fit: "○",
      confidence: 62,
      estimate: 4_400_000,
      dailyAdvance: 7,
      durationDays: 6,
      rationale: ["土質データ未取得のため、標準土質（砂質土 区分B）を仮定した暫定判定"],
      cautions: ["土質調査結果の提出を依頼し、確定判定は再度実施"],
      references: [
        { doc: "積算資料 2026年版", page: "p.12 表3-2", label: "土質区分と日進量" },
      ],
    },
    reviewer: "積算担当 A",
    reviewerNote: "暫定回答として送付。ボーリングデータ待ち。",
  },
];

export const knowledgeCandidates: KnowledgeCandidate[] = [
  {
    id: "KC-001",
    pattern: "礫混じり砂（礫径 20〜40mm）× φ100 指定",
    currentSpec: "参考資料 p.5：BM-S型（φ100）適用可（礫径 ≤ 20mm）",
    observedPractice: "φ200（BM-R型）へ変更して回答",
    occurrences: 14,
    period: "2023-04 〜 2026-08",
    suggestion:
      "参考資料 p.5 の BM-S型 適用条件に『礫径 20mm 超の場合は BM-R型（φ200）を選定』の注記を追加し、積算資料 表3-2 に礫径 20〜40mm の区分を新設する。",
    targetDoc: "2027年版 積算資料 / 参考資料（仕様書）",
    status: "提案中",
    evidence: [
      "INQ-2025-0314-02 ほか 13件で同一判断",
      "変更せず φ100 で施工した 2件はいずれも途中で機種変更（工期 +5日）",
    ],
  },
  {
    id: "KC-002",
    pattern: "粘性土 × 地下水位が管頂より 1.0m 以上高い",
    currentSpec: "積算資料 p.20：補助工法は『必要に応じて検討』",
    observedPractice: "薬液注入を必須として積算、工期 +2日",
    occurrences: 9,
    period: "2024-01 〜 2026-09",
    suggestion:
      "『検討』を『必須』に格上げし、標準歩掛に薬液注入 1式 と 工期補正 +2日 を明記する。",
    targetDoc: "2027年版 積算資料",
    status: "採用予定",
    evidence: ["INQ-2026-0911-02 で担当者が修正（学習キュー登録済み）", "過去 9件すべて同一判断"],
  },
  {
    id: "KC-003",
    pattern: "推進延長 60〜80m × BM-L型",
    currentSpec: "参考資料 p.9：最大推進延長 60m",
    observedPractice: "中間ジャッキ併用で 80m まで施工実績あり（6件）",
    occurrences: 6,
    period: "2022-06 〜 2026-05",
    suggestion:
      "最大推進延長を『60m（中間ジャッキ併用時 80m）』へ改定し、中間ジャッキの歩掛を追加する。",
    targetDoc: "2027年版 参考資料（仕様書）",
    status: "保留",
    evidence: ["6件中 1件で推力超過によりやり直し。条件付き採用を検討"],
  },
  {
    id: "KC-004",
    pattern: "到達側 既設人孔 × φ150 以上",
    currentSpec: "記載なし",
    observedPractice: "人孔内壁のコア抜き径を φ+100mm で指定",
    occurrences: 21,
    period: "2021-10 〜 2026-08",
    suggestion: "参考資料に『到達人孔 コア抜き径 = 管径 + 100mm』を標準として明記する。",
    targetDoc: "2027年版 参考資料（仕様書）",
    status: "採用予定",
    evidence: ["電話問い合わせの約 15% がこの質問。明記により問い合わせ削減が見込める"],
  },
];

export const qualityIssues: QualityIssue[] = [
  {
    id: "QI-001",
    type: "抜け漏れ",
    severity: "高",
    doc: "積算資料 2026年版",
    location: "p.18 表5-1 機種別標準歩掛",
    description: "BM-R型 の φ250 行で『日進量（m/日）』が空欄。φ200・φ300 は記載あり。",
    suggestion: "φ200（5m/日）と φ300（4m/日）の間で 4.5m/日 が妥当。過去実績 8件の平均は 4.6m/日。",
    resolved: false,
  },
  {
    id: "QI-002",
    type: "外れ値",
    severity: "高",
    doc: "積算資料 2026年版",
    location: "p.22 表6-3 労務単価",
    description: "『礫層 世話役』の単価が他の土質区分の 3.2倍。桁の入力ミスの可能性。",
    suggestion: "他区分は 28,000〜31,000円。当該セルは 96,000円 → 29,600円 の誤記と推定。",
    resolved: false,
  },
  {
    id: "QI-003",
    type: "不整合",
    severity: "中",
    doc: "積算資料 2026年版 / 参考資料（仕様書）",
    location: "積算 p.9 表2-1 ／ 仕様書 p.7",
    description: "BM-M型 の機械質量が積算資料では 1,850kg、仕様書では 1,920kg と異なる。",
    suggestion: "2025年のマイナーチェンジ後の質量（1,920kg）に統一。積算側の更新漏れと推定。",
    resolved: false,
  },
  {
    id: "QI-004",
    type: "改定漏れ",
    severity: "中",
    doc: "参考資料（仕様書）",
    location: "p.15 補助工法",
    description: "2025年版で廃止された『高圧噴射攪拌 A工法』の記載が残存。",
    suggestion: "該当段落を削除し、現行の B工法 の記載へ差し替え。",
    resolved: false,
  },
  {
    id: "QI-005",
    type: "抜け漏れ",
    severity: "低",
    doc: "積算資料 2026年版",
    location: "p.31 付表",
    description: "到達立坑 φ2.0m の場合の機材搬出手順への参照番号が欠落。",
    suggestion: "参考資料 p.12 への参照を追記。",
    resolved: true,
  },
  {
    id: "QI-006",
    type: "不整合",
    severity: "低",
    doc: "積算資料 2026年版",
    location: "p.12 表3-2 ／ p.14 表3-4",
    description: "『砂質土 区分B』の N値範囲が 表3-2 では 8〜15、表3-4 では 8〜12 と異なる。",
    suggestion: "表3-4 に合わせて 8〜12 へ統一（区分C との重複を解消）。",
    resolved: true,
  },
];

export const modelProviders: ModelProvider[] = [
  {
    id: "claude",
    name: "Claude（フロンティアモデル）",
    vendor: "Anthropic API",
    role: "主系",
    status: "稼働中",
    latencyMs: 2100,
    monthlyCost: 12_400,
    note: "積算判定・根拠生成・図面読取（マルチモーダル）",
  },
  {
    id: "gpt",
    name: "GPT（フロンティアモデル）",
    vendor: "OpenAI API",
    role: "副系",
    status: "待機",
    latencyMs: 2400,
    monthlyCost: 5_840,
    note: "主系の障害・提供終了時に自動切替。品質チェックの二重確認にも使用",
  },
  {
    id: "local",
    name: "ローカル小型モデル",
    vendor: "社内サーバー（オンプレ）",
    role: "緊急予備（ローカル）",
    status: "待機",
    latencyMs: 6800,
    monthlyCost: 0,
    note: "外部 API 断時に『ぎりぎり受け答えできる予備』として動作。精度は限定的",
  },
];

export const manualJobs: ManualJob[] = [
  {
    id: "MJ-001",
    title: "BM-M型 立坑内据付・芯出し作業",
    videoLength: "12:34",
    uploadedAt: "2026-09-10",
    progress: 100,
    status: "生成済み",
    steps: [
      { no: 1, title: "据付架台の搬入", body: "クレーンで据付架台を立坑底へ降ろし、発進方向に対して基準墨に合わせて仮置きする。", timestamp: "00:42" },
      { no: 2, title: "レベル調整", body: "架台四隅のジャッキボルトで水平を出す。水準器で前後左右 ±1mm 以内に調整。", timestamp: "03:15" },
      { no: 3, title: "本体の据付", body: "削進機本体を架台に載せ、固定ボルト 8本 を対角順に本締めする（トルク 120N·m）。", timestamp: "05:50" },
      { no: 4, title: "芯出し", body: "トランシットで発進方向の芯を確認。レーザーターゲットの中心が計画線上にあることを確認する。", timestamp: "08:20" },
      { no: 5, title: "反力受けの設置", body: "後方反力受けを立坑壁に密着させ、隙間はライナープレートで調整する。", timestamp: "10:48" },
    ],
  },
  {
    id: "MJ-002",
    title: "推進管の接続・シール確認",
    videoLength: "08:11",
    uploadedAt: "2026-09-12",
    progress: 62,
    status: "生成中",
  },
  {
    id: "MJ-003",
    title: "到達後の機体撤去・洗浄",
    videoLength: "15:02",
    uploadedAt: "2026-09-12",
    progress: 0,
    status: "未着手",
  },
];

export const dashboardStats = {
  todayInquiries: 10,
  pendingReview: 3,
  approvedWithoutEdit: 78, // %
  avgFirstAnswerMin: 4,
  legacyAvgFirstAnswerMin: 35,
  learningQueue: 5,
  monthlyBudget: 50_000,
  monthlyUsed: 18_240,
};

export const phases = [
  {
    no: "第0",
    name: "動画→作業マニュアル自動生成",
    scope: "現場の作業動画から手順書を自動生成。作業員の引継ぎ・新人教育に活用。",
    period: "1〜1.5ヶ月",
    budget: "30〜50万円",
    status: "稼働中" as const,
    href: "/manuals",
  },
  {
    no: "第1",
    name: "AIの弟子入り（社内利用）",
    scope: "積算判定アシスト＋資料の抜け漏れ・外れ値チェック。AIが回答案を出し、担当者が確認。",
    period: "2〜3ヶ月",
    budget: "100万円前後",
    status: "稼働中" as const,
    href: "/inquiries",
  },
  {
    no: "第2",
    name: "図面直読＋標準仕様への昇格提案",
    scope: "設計図面をそのまま読み取り機種提案。例外対応を束ねて標準仕様へ昇格させる提案。",
    period: "要件次第",
    budget: "追加見積",
    status: "プレビュー" as const,
    href: "/drawings",
  },
  {
    no: "第3",
    name: "Web一次回答／AI向けデータセット整備",
    scope: "着手前の相談にWeb上でAIが一次回答。他社CAD搭載AIが読むための積算データを整備。",
    period: "要件次第",
    budget: "追加見積",
    status: "構想" as const,
    href: "/web-answer",
  },
];

// ---- 参照データ（AI が照らし合わせるナレッジ）----
export const knowledgeSources: KnowledgeSource[] = [
  {
    id: "KS-001",
    category: "積算資料",
    name: "積算資料_2026年版.pdf",
    fileType: "PDF",
    size: "18.4 MB",
    version: "2026年版",
    validFrom: "2026-04-01",
    volume: "48ページ",
    status: "取込済み",
    updatedAt: "2026-09-01",
    usedFor: "土質区分・日進量・標準歩掛・労務単価の照合（概算費用の算出根拠）",
  },
  {
    id: "KS-002",
    category: "参考資料（仕様書）",
    name: "参考資料_仕様書_2026年版.pdf",
    fileType: "PDF",
    size: "9.7 MB",
    version: "2026年版",
    validFrom: "2026-04-01",
    volume: "32ページ",
    status: "取込済み",
    updatedAt: "2026-09-01",
    usedFor: "各機種の適用範囲（管径・延長・礫径・土質）の判定",
  },
  {
    id: "KS-003",
    category: "判断履歴",
    name: "積算判定履歴_2023-2026.xlsx",
    fileType: "Excel",
    size: "2.1 MB",
    validFrom: "2023-04-01",
    volume: "412件",
    status: "取込済み",
    updatedAt: "2026-09-10",
    usedFor: "類似案件の検索、仕様書との差分（経験則）の抽出、標準化候補の集計",
    note: "2023-04 の仕様変更以降のみ取り込み。担当者コメント列を「判断理由」として学習",
  },
  {
    id: "KS-004",
    category: "判断履歴",
    name: "積算判定履歴_2019-2023.xlsx",
    fileType: "Excel",
    size: "3.4 MB",
    validFrom: "2019-04-01",
    validTo: "2023-03-31",
    volume: "568件",
    status: "除外",
    updatedAt: "2026-09-10",
    usedFor: "—",
    note: "旧仕様（BM-M型 改良前・旧歩掛）のデータ。混ぜると誤った出力になるため参照対象から除外",
  },
  {
    id: "KS-005",
    category: "施工実績",
    name: "協会_施工実績台帳_2024-2026.csv",
    fileType: "CSV",
    size: "640 KB",
    validFrom: "2024-01-01",
    volume: "186件",
    status: "取込済み",
    updatedAt: "2026-08-28",
    usedFor: "実績日進量・工期実績による注意点の補強（例：N値 5 以下で工期 +2日）",
  },
  {
    id: "KS-006",
    category: "機種カタログ",
    name: "BMシリーズ_機種カタログ_2025.pdf",
    fileType: "PDF",
    size: "24.0 MB",
    version: "2025年版",
    volume: "20ページ",
    status: "要確認",
    updatedAt: "2026-09-11",
    usedFor: "機械質量・寸法・必要立坑径の照合",
    note: "BM-M型 の機械質量が積算資料と不一致（品質チェック QI-003）。どちらを正とするか確認待ち",
  },
  {
    id: "KS-007",
    category: "土質・地盤データ",
    name: "地盤区分早見表_協会技術委員会.xlsx",
    fileType: "Excel",
    size: "310 KB",
    volume: "1シート",
    status: "取込中",
    updatedAt: "2026-09-12",
    usedFor: "柱状図の土質名・N値から積算資料の土質区分（A〜D）への変換",
  },
];

export const sourceCategoryDesc: Record<KnowledgeSource["category"], string> = {
  積算資料: "概算費用の算出根拠。年度版ごとに管理し、有効期間で切り替える",
  "参考資料（仕様書）": "機種の適用範囲。仕様書との差分（経験則）を検出する基準",
  判断履歴: "過去の担当者の判断。類似案件の検索と経験則の抽出に使う。仕様変更前は除外",
  施工実績: "実際の日進量・工期。注意点の根拠を補強する",
  機種カタログ: "機械の寸法・質量。立坑条件との整合に使う",
  "土質・地盤データ": "柱状図の読み替えルール。図面直読の精度に効く",
};
